### ISSUE TITLE
Burn Munki recipe breaks on makepkginfo

### ISSUE THREAD

**Issue by aysiu** [autopkg/aysiu-recipes#7]
```
MunkiImporter: KeyError: 'name'
creating pkginfo for /Users/USERNAME/Library/AutoPkg/Cache/com.github.aysiu.munki.Burn/Burn/Burn/Burn.app failed: Traceback (most recent call last):
  File "/usr/local/munki/makepkginfo", line 1166, in <module>
    main()
  File "/usr/local/munki/makepkginfo", line 1144, in main
    item = catinfo['name']
KeyError: 'name'

Failed.
Receipt written to /Users/USERNAME/Library/AutoPkg/Cache/com.github.aysiu.munki.Burn/receipts/Burn-receipt-20161007-111921.plist

The following recipes failed:
    Burn.munki
        Error in com.github.aysiu.munki.Burn: Processor: MunkiImporter: Error: creating pkginfo for /Users/USERNAME/Library/AutoPkg/Cache/com.github.aysiu.munki.Burn/Burn/Burn/Burn.app failed: Traceback (most recent call last):
  File "/usr/local/munki/makepkginfo", line 1166, in <module>
    main()
  File "/usr/local/munki/makepkginfo", line 1144, in main
    item = catinfo['name']
KeyError: 'name'
```

**Comment by aysiu** [comment]
Fixed. Just needed the correct path and DmgCreator.
